name: birds

region: fra

services:
  - build_command: yarn build
    environment_slug: node-js
    github:
      branch: master
      deploy_on_push: true
      repo: SoapboxSocial/Birds
    http_port: 1337
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: api
    name: api
    routes:
      - path: /api
    run_command: yarn start

static_sites:
  - environment_slug: html
    github:
      branch: master
      deploy_on_push: true
      repo: SoapboxSocial/Birds
    name: frontend
    source_dir: frontend
    routes:
      - path: /
